"""'add_chores_table'

Revision ID: db12c4a094d4
Revises: 
Create Date: 2026-02-25 14:51:29.629901

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'db12c4a094d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chore_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chores_room_id'), 'chores', ['room_id'], unique=False)
    op.create_index(op.f('ix_chores_user_id'), 'chores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chores_user_id'), table_name='chores')
    op.drop_index(op.f('ix_chores_room_id'), table_name='chores')
    op.drop_table('chores')
    # ### end Alembic commands ###
